<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrbitTerm.Application\OrbitTerm.Application.csproj" />
    <ProjectReference Include="..\OrbitTerm.Terminal\OrbitTerm.Terminal.csproj" />
  </ItemGroup>
</Project>
